# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
    PACKAGE_PREFIX: 1
    OCTOPUS_PROJECT_NAME: EnthisuasticPromotions
    OCTOPUS_SPACE_NAME: OctopusServer
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Install Pester
        id: install-pester
        run: Install-Module "Pester" -Force
       
      - name: Run Pester Tests
        id: pester-tests
        run: Invoke-Pester

      - name: Set version
        id: set-version
        run: echo "::set-env name=PACKAGE_VERSION::$PACKAGE_PREFIX.$GITHUB_RUN_NUMBER"
    
      - name: Make package directories
        run: mkdir -p ./packagesoutput/          
    
      - name: Install Octopus CLI
        run: |
          sudo apt update && sudo apt install --no-install-recommends gnupg curl ca-certificates apt-transport-https && \
          curl -sSfL https://apt.octopus.com/public.key | sudo apt-key add - && \
          sudo sh -c "echo deb https://apt.octopus.com/ stable main > /etc/apt/sources.list.d/octopus.com.list" && \
          sudo apt update && sudo apt install octopuscli 
          
      - name: Package and Push to Octopus
        run: |
          octo pack --id="MyApp.Web" --format="Zip" --version="$PACKAGE_VERSION" --basePath="./packagesoutput/MyApp.Web" --outFolder="./packages"

          octo push --package="./packages/MyApp.Web.$PACKAGE_VERSION.zip" --server="${{ secrets.OCTOPUS_SERVER }}" --apiKey="${{ secrets.OCTOPUS_APIKEY }}"
